#!/bin/bash
## Install Apache, PHP7.0, MYSQL, phpMyAdmin
## Sys Admin Muhammad Rifky Abimayu 
## Error Code? Call saya@rifky.tech

echo -n " Detection OS : " ; lsb_release -ds
sleep 3s

# Install Apache Web Server Use Taksel
sudo tasksel apache

# Install PHP, Mysql, Libapache2, dan phpMyAdmin
sudo apt-get -y install php7.0-fpm
sudo apt-get install libapache2-mod-php7.0
sudo apt-get -y install mariadb-server mysql-client 




echo "#########################################################################################################################"
echo " "
echo " "
echo " "
echo " Pada Install phpmyadmin, berikut ada 2 pilihan opsi :
              - pada opsi (Web Server to reconfigure automatically) : <--Pilih Apache
              dan Menekan TAB lalu Ok
              - pada opsi (Configure database for phpmyadmin with dbconfig-common) <--Pilih
              No "

echo " "
echo " "
echo " "
echo "#########################################################################################################################"
sleep 5s




sudo apt-get -y install phpmyadmin

# Mengaktifkan Modul PHP7.0

sudo a2enconf php7.0-fpm
sudo service apache2 reload
sudo a2enmod proxy_fcgi setenvif
sudo service apache2 reload

# Konfigurasi & Install vsftpd
sudo chown -R pi /var/www/html/
sudo apt-get -y install vsftpd
sudo rm -rf /etc/vsftpd.conf
sudo cp -r vsftpd.conf /etc/

# Konfigurasi php.ini
sudo mv /etc/php/7.0/fpm/php.ini /etc/php/7.0/fpm/php.ini.swp
sudo cp -r php.ini /etc/php/7.0/fpm/
sudo mv /etc/php/7.0/apache2/php.ini /etc/php/7.0/apache2/php.ini.swp
sudo cp -r php2.ini /etc/php/7.0/apache2/php.ini

# Creat phpinfo
sudo cp -r info.php /var/www/html/

# Konfigurasi rc.local agar start ssh
sudo rm -rf /etc/rc.local
sudo cp -r rc.local /etc
sudo chmod +x /etc/rc.local

# Set Password Mysql
sudo mysql_secure_installation


echo "#########################################################################################################################"
echo " "
echo " "
echo " "
echo " Langkah ini harus dilakukan, yaitu 
      - masuk sebagai root, lalu ketik "mysql -u root"
      - masukan perintah berikut di mysql :
      
      use mysql;
      update user set plugin='' where User='root';
      flush privileges;
      exit;
      
      
      jika sudah, berikut list tested nya :
      - http://localhost/info.php <-- untuk cek bahwa php telah terinstall
      - http://localhost/phpmyadmin <-- untuk cek bahwa phpmyadmin telah terinstall
      
      Login phpmyadmin nya gunakan :
      user : root
      pass : (sesuai dengan kamu buat)
     
     "  
      
echo "Terima Kasih,.. Menemukan Error Perintah ? send feedback : saya@rifky.tech"
echo " "
echo " "
echo " "
echo "#########################################################################################################################"
sudo chmod 755 hapus
